2024-10-25 17:57:41,926 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\kolyu\Documents\pythonProject\practical_exercises_12\tests_12_4.py", line 21, in test_run
    runner_2 = rt.Runner(5)
               ^^^^^^^^^^^^
  File "C:\Users\kolyu\Documents\pythonProject\practical_exercises_12\running_tournament_1.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-25 17:57:41,930 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\kolyu\Documents\pythonProject\practical_exercises_12\tests_12_4.py", line 10, in test_walk
    runner_1 = rt.Runner('Maxim', -5)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kolyu\Documents\pythonProject\practical_exercises_12\running_tournament_1.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
